# Generated by Django 5.0.7 on 2024-07-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_location_booking_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="location",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(name="Location",),
    ]
