# Generated by Django 5.0.7 on 2024-07-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_booking_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="number_of_people",
            field=models.PositiveIntegerField(),
        ),
    ]
