# Generated by Django 5.0.7 on 2024-07-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_booking_number_of_people"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking", name="number_of_people", field=models.IntegerField(),
        ),
    ]
