# Generated by Django 5.0.7 on 2024-07-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_booking_number_of_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='place',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
